### PR TITLE
Handle commit hash versions

### LINKED ISSUE #199: Handle commit hash versions properly
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Commit hashes are not being dealt with properly when used as version identifier. The following error is thrown as can be seen on the [repro link](https://github.com/nearform/github-action-notify-release/runs/6224605381?check_suite_focus=true) when there's no target specified: 

```
Run fastify/github-action-merge-dependabot@v3
Error: Cannot read properties of null (reading 'raw')
```

### PR DESCRIPTION
**Pull request by guilhermelimak**
This change re-add support for commit hash versions on both PR diff and title (which I believe were removed after the PR diff changes). They will be merged independently of the target option since the hash doesn't have that information.

#### Checklist
- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Closes #199 
Closes https://github.com/nearform/github-action-notify-release/pull/189

### CODE REVIEW

File: src/action.js [hunk 1]
```diff
@@ -105,9 +109,25 @@ function parsePrTitle(pullRequest) {
...
     throw new Error('Error while parsing PR title, expected: `bump <package> from <old-version> to <new-version>`')
   }
-  const [, oldVersion, newVersion] = match
+
+  const [, oldVersion, newVersion] = match.map(t => t.replace(/`/g, ''))
 
   const packageName = getPackageName(pullRequest.head.ref)
 
-  return { [packageName]: { delete: semverCoerce(oldVersion).raw, insert: semverCoerce(newVersion).raw } }
+  if (semverCoerce(oldVersion) && semverCoerce(newVersion)) {
```
Comment (simoneb) [inline src/action.js:117]: there's a better way to write this whole section using conditional chaining, let's leverage that

File: src/util.js [hunk 2]
```diff
@@ -54,3 +54,7 @@ exports.getPackageName = (branchName) => {
 
   return packageName
 }
+
+exports.isCommitHash = function(version) {
+  return /^[\w]{7}$/.test(version)
```
Comment (simoneb) [inline src/util.js:59]: this doesn't feel very robust. how do we know it will be always 7 chars? we don't!

**Review by simoneb — CHANGES_REQUESTED** [review]

File: package.json [hunk 3]
```diff
@@ -6,7 +6,7 @@
   "scripts": {
     "build": "ncc build src/index.js",
     "lint": "eslint .",
-    "test": "tap",
+    "test": "tap test/**.test.js",
```
[the remark this answers is not in the document]
Comment (guilhermelimak) [reply package.json:9]: By default it uses `test/*.js` which includes [this file](https://github.com/fastify/github-action-merge-dependabot/blob/main/test/moduleChanges.js) which prints a warning because it doesn't have any actual tests on it.

File: src/action.js (hunk 1 above)
Comment (guilhermelimak) [reply src/action.js:117]: I guess it could be improved, but not by just doing something like this (as it's what I'm assuming you mean:
```js
return {
  [packageName]: {
    delete: semverCoerce(oldVersion)?.raw ?? oldVersion,
    insert: semverCoerce(newVersion)?.raw ?? newVersion
  }
}
```
I just noticed that `semver.coerce` sometimes will be a bit too loose when handling some inputs which caused some of the tests to ffail, for instance it will parse cc**221**b3 as **221**.0.0 and such. I'll use a ternary based on `semver.valid` which will reduce the code repetition.

I'm just fixing the code coverage that was reduced after this change.

File: src/util.js (hunk 2 above)
Comment (guilhermelimak) [reply src/util.js]: I've updated it to [this](https://github.com/fastify/github-action-merge-dependabot/pull/200/files#diff-9c0ec1b0a889e599f3ff81590864dd9dc65684a86b41f1da75acc53fafed12e3R70). Do you think that's alright?

**Review by simoneb — APPROVED** [review]

File: test/util.test.js [hunk 4]
```diff
@@ -40,3 +40,18 @@ tap.test('getPackageName should get package name from branch', async t => {
 tap.test('getPackageName should throw an error for invalid branch names', async t => {
   t.throws(() => getPackageName("invalidbranchname"), new Error('Invalid branch name, package name or version not found'))
 })
+
+tap.test('isCommitHash should detect 7 digit commit hashes properly', async t => {
```
Comment (simoneb) [inline test/util.test.js:44]: this test name is inaccurate

**Comment by guilhermelimak** [comment]
> let's merge and cut a patch release please @guilhermelimak

I don't have write permissions to this repo
