### PR TITLE
fix: improve PR Title parsing, handle invalid inputs

### LINKED ISSUE #185: Improve handling of invalid PR titles
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

- [x] Improve handling of invalid PR titles, it should throw an error instead of silently approving the PR (as per discussion with @simoneb)
- [x] Parse package name from branch name instead of title to avoid namespace issues
- [x] Fix related tests

### PR DESCRIPTION
**Pull request by guilhermelimak**
Improve handling of invalid PR titles.
Parse package name from branch name to avoid issues.

Closes #185

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: src/action.js [hunk 1]
```diff
@@ -94,23 +94,23 @@ function isAMajorReleaseBump(change) {
...
-    return {}
+    throw new Error('Error while parsing PR title, expected: `bump <package> from <old-version> to <new-version>`')
   }
+  const [, oldVersion, newVersion] = match
 
-  const [, packageName, oldVersion, newVersion] = match
+  // Get package name from branch
+  // dependabot branch names are in format "dependabot/npm_and_yarn/pkg-0.0.1"
+  // or "dependabot/github_actions/fastify/github-action-merge-dependabot-2.6.0"
+  const packageName = pullRequest.head.ref.split('/').pop().split('-').slice(0, -1).join('-')
```
Comment (simone-sanfratello) [inline src/action.js:113]: I'd put this logic in a function like `getPackageName(pullRequest.head.ref)` or something, so it can be unit tested massively and easily

Comment (climba03003) [reply src/action.js:113]: Example PR for invalid title
https://github.com/austins/smoothnanners-web/pull/17
` dependabot/npm_and_yarn/react-and-react-dom-18.0.0`
https://github.com/wallabag/wallabag/pull/5537
`dependabot/npm_and_yarn/stylelint-and-stylelint-config-standard-and-stylelint-scss-14.2.0]`

Comment (guilhermelimak) [reply src/action.js:113]: > Example PR for invalid title [austins/smoothnanners-web#17](https://github.com/austins/smoothnanners-web/pull/17) ` dependabot/npm_and_yarn/react-and-react-dom-18.0.0` [wallabag/wallabag#5537](https://github.com/wallabag/wallabag/pull/5537) `dependabot/npm_and_yarn/stylelint-and-stylelint-config-standard-and-stylelint-scss-14.2.0`

Those are actually not affected by this I don't think. Since they're package.json changes they will be parsed from the diff [here](https://github.com/fastify/github-action-merge-dependabot/blob/main/src/moduleVersionChanges.js#L44). This function will only apply to changes that are not on package.json (e.g. github workflow files)

File: src/util.js [hunk 2]
```diff
@@ -37,3 +37,10 @@ exports.getInputs = () => ({
   TARGET: getTargetInput(core.getInput('target')),
   PR_NUMBER: core.getInput('pr-number'),
 })
+
+exports.getPackageName = (branchName) => {
```
Comment (simone-sanfratello) [inline src/util.js:41]: comment should be at function, not inside, better if in jsdoc format

File: test/util.test.js [hunk 3]
```diff
@@ -27,3 +28,11 @@ tap.test('MERGE_METHOD should be correct for valid input', async t => {
   })
   t.equal(getInputs().MERGE_METHOD, 'merge')
 })
+
+tap.test('getPackageName should get package name from branch', async t => {
```
Comment (simone-sanfratello) [inline test/util.test.js:32]: should test also for inputs that does not fit happy output
should test one case at time

**Review by simone-sanfratello — APPROVED** [review]

**Review by simoneb — APPROVED** [review]
