### PR TITLE
Fix GHES support

### LINKED ISSUE #363: Add GHES support
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently automerging dependabot PRs does not work in GitHub Enterprise Server environment.
You'll get error from `dependabot/fetch-metadata@v1`.
```
Warning: Dependabot's commit signature is not verified, refusing to proceed.
Error: PR is not from Dependabot, nothing to do.
```

I believe this could be easily solved just by passing `skip-commit-verification` to `dependabot/fetch-metadata@v1` (https://github.com/dependabot/fetch-metadata) action.

I'd propose adding new input `skip-commit-verification` and then passing it to `dependabot/fetch-metadata@v1`.

### Motivation

Support for GHES.

### Example

```yml
steps:
  - name: Automerge GHES dependabot PR
    uses: fastify/github-action-merge-dependabot@v3
    with:
      skip-commit-verification: true
```

### LINKED ISSUE #365: Release pending!
### Pending commits since release [v3.5.4](https://github.com/fastify/github-action-merge-dependabot/releases/tag/v3.5.4)

Based on the following commits, a **patch** release is recommended.

Unreleased commits have been found which are pending release, please publish the changes.

  * [a4226d3](https://github.com/fastify/github-action-merge-dependabot/commit/a4226d30b3ae46fd135d9b615305e0759ce43144) Support GHES with skip-commit-verification (#364)
  * [7213647](https://github.com/fastify/github-action-merge-dependabot/commit/72136475658f0958238a87eb6f59ed855320f64d) chore(deps): bump actions-toolkit from &#x60;51eb375&#x60; to &#x60;d06c29a&#x60; (#362)
  * [b1add48](https://github.com/fastify/github-action-merge-dependabot/commit/b1add4868219a37b0cc3e1a1fa3c8e977876c9b2) chore(deps-dev): bump @vercel/ncc from 0.36.0 to 0.36.1 (#358)
  * [314cdcc](https://github.com/fastify/github-action-merge-dependabot/commit/314cdccb5bd321e0f20bf7ad72c00455f0a2bd62) chore(deps-dev): bump eslint from 8.32.0 to 8.33.0 (#357)
  * [f42080c](https://github.com/fastify/github-action-merge-dependabot/commit/f42080cc2235f9c957dd555d715f1bab3da2d0b8) chore(deps): bump actions-toolkit from &#x60;90f26b3&#x60; to &#x60;51eb375&#x60; (#356)
  * [81f0f07](https://github.com/fastify/github-action-merge-dependabot/commit/81f0f073f71666d22085ad981e94ba045119cefe) chore(deps): bump actions-toolkit from &#x60;2e9e15f&#x60; to &#x60;90f26b3&#x60; (#353)
  * [b22d4c6](https://github.com/fastify/github-action-merge-dependabot/commit/b22d4c6c3abb661decc5b97396626087719ad0e0) chore(deps-dev): bump prettier from 2.8.2 to 2.8.3 (#351)
  * [37ce061](https://github.com/fastify/github-action-merge-dependabot/commit/37ce0619e3d6157b2393e59894688c66586268bf) chore(deps-dev): bump tap from 16.3.3 to 16.3.4 (#349)
  * [34896e0](https://github.com/fastify/github-action-merge-dependabot/commit/34896e07bb9497090bdccec4b07ddfede97f1d46) chore(deps): bump actions-toolkit from &#x60;f03f02c&#x60; to &#x60;2e9e15f&#x60; (#350)
  * [e878e33](https://github.com/fastify/github-action-merge-dependabot/commit/e878e335bfbb1599a2bda5085ebd78b5700659de) chore(deps-dev): bump eslint from 8.31.0 to 8.32.0 (#348)
  * [6c28ea0](https://github.com/fastify/github-action-merge-dependabot/commit/6c28ea040dae489bdcf0cbb5c3bcd70952f22112) chore(deps-dev): bump prettier from 2.8.1 to 2.8.2 (#347)
  * [2a938a6](https://github.com/fastify/github-action-merge-dependabot/commit/2a938a6647488765a223cfdee66a2ba923c21a3e) chore(deps-dev): bump husky from 8.0.2 to 8.0.3 (#346)
  * [5dc260c](https://github.com/fastify/github-action-merge-dependabot/commit/5dc260c75218ead2346809e86234acc029caec33) chore(deps): bump actions-toolkit from &#x60;5a17f68&#x60; to &#x60;f03f02c&#x60; (#345)
  * [c500e1a](https://github.com/fastify/github-action-merge-dependabot/commit/c500e1aa01ae924afbcd7fc90f90a45f0f0ed689) chore(deps-dev): bump eslint-config-prettier from 8.5.0 to 8.6.0 (#344)
  * [bc0994c](https://github.com/fastify/github-action-merge-dependabot/commit/bc0994c459882617f5ad9219786a0d27d3a9c3a7) chore(deps-dev): bump tap from 16.3.2 to 16.3.3 (#343)

#### If you close the issue as **Not Planned**

- The notification will be snoozed for 7 days, starting when the issue is closed. After this period has passed, a new notification issue will be created the next time this action is run.

> Issue generated by [github-actions-notify-release](https://github.com/nearform/github-action-notify-release).

### PR DESCRIPTION
**Pull request by frequ**
Fixes #363

We got little further with the initial GHES support, but it still hits with the verifySignatures:
```
Warning: PR contains invalid dependabot commit signatures, skipping.
```

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by simoneb** [comment]
Thanks for the follow up. We need to be careful with this further changes as they open up surface for a potential attack, which is why we put in place commit verification. Therefore, before going on with this change I think it's worth taking some time to understand why you need this in the first place.

**Comment by frequ** [comment]
> Thanks for the follow up. We need to be careful with this further changes as they open up surface for a potential attack, which is why we put in place commit verification. Therefore, before going on with this change I think it's worth taking some time to understand why you need this in the first place.

Well, we are using this action in our public github for automerging depdendabot PRs and would like to use the same action in GHES as well. 

I do understand the potential security issues. I wonder if we could only allow skipping `verifyCommit` for GitHub Enterprise Server. E.g. check if `GITHUB_SERVER_URL` is set.

**Comment by simoneb** [comment]
What I would like to understand is why commits cannot be verifies in a GHES environment

**Comment by frequ** [comment]
Not sure why dependabot is not a verified committer in GHES, but something similar was done here: https://github.com/dependabot/fetch-metadata/pull/225

**Comment by frequ** [comment]
I was finally able to test this with GHES and can confirm that it fully works now.

**Comment by zetaab** [comment]
as customer for github enterprise server: we cannot fix how github is handling this in GHES. If github is allowing such PRs to their own organisation (dependabot https://github.com/dependabot/fetch-metadata/pull/225) I think they do understand that the problem is not easy to solve in GHES side

**Comment by simoneb** [comment]
> as customer for github enterprise server: we cannot fix how github is handling this in GHES. If github is allowing such PRs to their own organisation (dependabot [dependabot/fetch-metadata#225](https://github.com/dependabot/fetch-metadata/pull/225)) I think they do understand that the problem is not easy to solve in GHES side

Thanks for this clarification, this indeed gives us more confidence that we can do this change. Please allow some time for somebody from the team to review.

File: src/action.js [hunk 1]
```diff
@@ -57,12 +58,14 @@ module.exports = async function run({
...
 
-    try {
-      await verifyCommits(commits)
-    } catch {
-      return logWarning(
-        'PR contains invalid dependabot commit signatures, skipping.'
-      )
+    if (!SKIP_COMMIT_VERIFICATION) {
+      try {
+        await verifyCommits(commits)
```
Comment (davideroffo) [inline src/action.js:63]: Not related to your changes, but I don't see any valid reason to use `await` here. The `verifyCommits` function is not returning a `Promise`.

**Review by davideroffo — APPROVED** [review]
LGTM, just left a comment not related to your changes but that we can address in this PR.

File: src/action.js (hunk 1 above)
Comment (davideroffo) [inline src/action.js:63]: Not related to your changes, but I don't see any valid reason to use `await` since the `verifyCommits` is not returning a `Promise`.

Comment (frequ) [reply src/action.js:63]: Removing `await` seems to break the tests

Comment (davideroffo) [reply src/action.js:63]: Yes, you need to update the tests as well. They are returning Promise.rejects instead of throwsException.

Comment (frequ) [reply src/action.js]: Updated

**Review by davideroffo — CHANGES_REQUESTED** [review]
We have noticed that the `SKIP_COMMIT_VERIFICATION` is parsed as a `String` instead of a `boolean`. For this reason, the `verifyCommits` will always be skipped.

You can try it easily by logging this in your branch:

```javascript
if (typeof SKIP_COMMIT_VERIFICATION === 'boolean') {
    console.log('skip-commit-verification is a BOOLEAN!')
  } else if (typeof SKIP_COMMIT_VERIFICATION === 'string') {
    console.log('skip-commit-verification is a STRING!')
  }
```

Running the action you will see that the printed line will be:

```
skip-commit-verification is a STRING!
```

Can you fix this behaviour as well?

**Comment by frequ** [comment]
> We have noticed that the `SKIP_COMMIT_VERIFICATION` is parsed as a `String` instead of a `boolean`. For this reason, the `verifyCommits` will always be skipped.
> 
> 
> Can you fix this behaviour as well?

Good catch! Made a fix and extended tests to cover all the boolean inputs.

**Review by davideroffo — APPROVED** [review]
LGTM
